SELECT DOCUMENTOS.*, 
(DOCUMENTOS.CODIGO||LPAD(DOCUMENTOS.CORRELATIVO,3,0)) AS CODIGO_DOCUMENTO, 
TIPO_SISTEMAS.NOMBRE AS NOMBRE_SISTEMA, TIPO_SISTEMAS.ABREVIATURA AS ABR_SISTEMA,
PROCESOS.NOMBRE AS NOMBRE_PROCESO, PROCESOS.ABREVIATURA AS ABR_PROCESO,
TIPO_DOCUMENTOS.NOMBRE AS NOMBRE_TIPO_DOCTO, TIPO_DOCUMENTOS.ABREVIATURA AS ABR_TIPO_DOCTO,
ESTADO_DOCUMENTOS.NOMBRE AS NOMBRE_ESTADO_DOCTO
FROM DOCUMENTOS 
LEFT JOIN TIPO_SISTEMAS ON(DOCUMENTOS.TIPO_SISTEMA_ID=TIPO_SISTEMAS.ID)
LEFT JOIN PROCESOS ON(DOCUMENTOS.PROCESO_ID=PROCESOS.ID)
LEFT JOIN TIPO_DOCUMENTOS ON(DOCUMENTOS.TIPO_DOCUMENTO_ID=TIPO_DOCUMENTOS.ID)
LEFT JOIN ESTADO_DOCUMENTOS ON(DOCUMENTOS.ESTADO_DOCUMENTO_ID=ESTADO_DOCUMENTOS.ID)