require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/estado_documentos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EstadoDocumento. As you add validations to EstadoDocumento, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EstadoDocumento.create! valid_attributes
      get estado_documentos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      estado_documento = EstadoDocumento.create! valid_attributes
      get estado_documento_url(estado_documento)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_estado_documento_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      estado_documento = EstadoDocumento.create! valid_attributes
      get edit_estado_documento_url(estado_documento)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EstadoDocumento" do
        expect {
          post estado_documentos_url, params: { estado_documento: valid_attributes }
        }.to change(EstadoDocumento, :count).by(1)
      end

      it "redirects to the created estado_documento" do
        post estado_documentos_url, params: { estado_documento: valid_attributes }
        expect(response).to redirect_to(estado_documento_url(EstadoDocumento.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EstadoDocumento" do
        expect {
          post estado_documentos_url, params: { estado_documento: invalid_attributes }
        }.to change(EstadoDocumento, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post estado_documentos_url, params: { estado_documento: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested estado_documento" do
        estado_documento = EstadoDocumento.create! valid_attributes
        patch estado_documento_url(estado_documento), params: { estado_documento: new_attributes }
        estado_documento.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the estado_documento" do
        estado_documento = EstadoDocumento.create! valid_attributes
        patch estado_documento_url(estado_documento), params: { estado_documento: new_attributes }
        estado_documento.reload
        expect(response).to redirect_to(estado_documento_url(estado_documento))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        estado_documento = EstadoDocumento.create! valid_attributes
        patch estado_documento_url(estado_documento), params: { estado_documento: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested estado_documento" do
      estado_documento = EstadoDocumento.create! valid_attributes
      expect {
        delete estado_documento_url(estado_documento)
      }.to change(EstadoDocumento, :count).by(-1)
    end

    it "redirects to the estado_documentos list" do
      estado_documento = EstadoDocumento.create! valid_attributes
      delete estado_documento_url(estado_documento)
      expect(response).to redirect_to(estado_documentos_url)
    end
  end
end
