require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/etapa_documentos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EtapaDocumento. As you add validations to EtapaDocumento, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EtapaDocumento.create! valid_attributes
      get etapa_documentos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      etapa_documento = EtapaDocumento.create! valid_attributes
      get etapa_documento_url(etapa_documento)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_etapa_documento_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      etapa_documento = EtapaDocumento.create! valid_attributes
      get edit_etapa_documento_url(etapa_documento)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EtapaDocumento" do
        expect {
          post etapa_documentos_url, params: { etapa_documento: valid_attributes }
        }.to change(EtapaDocumento, :count).by(1)
      end

      it "redirects to the created etapa_documento" do
        post etapa_documentos_url, params: { etapa_documento: valid_attributes }
        expect(response).to redirect_to(etapa_documento_url(EtapaDocumento.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EtapaDocumento" do
        expect {
          post etapa_documentos_url, params: { etapa_documento: invalid_attributes }
        }.to change(EtapaDocumento, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post etapa_documentos_url, params: { etapa_documento: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested etapa_documento" do
        etapa_documento = EtapaDocumento.create! valid_attributes
        patch etapa_documento_url(etapa_documento), params: { etapa_documento: new_attributes }
        etapa_documento.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the etapa_documento" do
        etapa_documento = EtapaDocumento.create! valid_attributes
        patch etapa_documento_url(etapa_documento), params: { etapa_documento: new_attributes }
        etapa_documento.reload
        expect(response).to redirect_to(etapa_documento_url(etapa_documento))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        etapa_documento = EtapaDocumento.create! valid_attributes
        patch etapa_documento_url(etapa_documento), params: { etapa_documento: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested etapa_documento" do
      etapa_documento = EtapaDocumento.create! valid_attributes
      expect {
        delete etapa_documento_url(etapa_documento)
      }.to change(EtapaDocumento, :count).by(-1)
    end

    it "redirects to the etapa_documentos list" do
      etapa_documento = EtapaDocumento.create! valid_attributes
      delete etapa_documento_url(etapa_documento)
      expect(response).to redirect_to(etapa_documentos_url)
    end
  end
end
