require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/etapa_solicitudes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EtapaSolicitud. As you add validations to EtapaSolicitud, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EtapaSolicitud.create! valid_attributes
      get etapa_solicitudes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      etapa_solicitud = EtapaSolicitud.create! valid_attributes
      get etapa_solicitud_url(etapa_solicitud)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_etapa_solicitud_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      etapa_solicitud = EtapaSolicitud.create! valid_attributes
      get edit_etapa_solicitud_url(etapa_solicitud)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EtapaSolicitud" do
        expect {
          post etapa_solicitudes_url, params: { etapa_solicitud: valid_attributes }
        }.to change(EtapaSolicitud, :count).by(1)
      end

      it "redirects to the created etapa_solicitud" do
        post etapa_solicitudes_url, params: { etapa_solicitud: valid_attributes }
        expect(response).to redirect_to(etapa_solicitud_url(EtapaSolicitud.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EtapaSolicitud" do
        expect {
          post etapa_solicitudes_url, params: { etapa_solicitud: invalid_attributes }
        }.to change(EtapaSolicitud, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post etapa_solicitudes_url, params: { etapa_solicitud: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested etapa_solicitud" do
        etapa_solicitud = EtapaSolicitud.create! valid_attributes
        patch etapa_solicitud_url(etapa_solicitud), params: { etapa_solicitud: new_attributes }
        etapa_solicitud.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the etapa_solicitud" do
        etapa_solicitud = EtapaSolicitud.create! valid_attributes
        patch etapa_solicitud_url(etapa_solicitud), params: { etapa_solicitud: new_attributes }
        etapa_solicitud.reload
        expect(response).to redirect_to(etapa_solicitud_url(etapa_solicitud))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        etapa_solicitud = EtapaSolicitud.create! valid_attributes
        patch etapa_solicitud_url(etapa_solicitud), params: { etapa_solicitud: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested etapa_solicitud" do
      etapa_solicitud = EtapaSolicitud.create! valid_attributes
      expect {
        delete etapa_solicitud_url(etapa_solicitud)
      }.to change(EtapaSolicitud, :count).by(-1)
    end

    it "redirects to the etapa_solicitudes list" do
      etapa_solicitud = EtapaSolicitud.create! valid_attributes
      delete etapa_solicitud_url(etapa_solicitud)
      expect(response).to redirect_to(etapa_solicitudes_url)
    end
  end
end
