require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/macro_procesos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MacroProceso. As you add validations to MacroProceso, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MacroProceso.create! valid_attributes
      get macro_procesos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      macro_proceso = MacroProceso.create! valid_attributes
      get macro_proceso_url(macro_proceso)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_macro_proceso_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      macro_proceso = MacroProceso.create! valid_attributes
      get edit_macro_proceso_url(macro_proceso)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MacroProceso" do
        expect {
          post macro_procesos_url, params: { macro_proceso: valid_attributes }
        }.to change(MacroProceso, :count).by(1)
      end

      it "redirects to the created macro_proceso" do
        post macro_procesos_url, params: { macro_proceso: valid_attributes }
        expect(response).to redirect_to(macro_proceso_url(MacroProceso.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MacroProceso" do
        expect {
          post macro_procesos_url, params: { macro_proceso: invalid_attributes }
        }.to change(MacroProceso, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post macro_procesos_url, params: { macro_proceso: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested macro_proceso" do
        macro_proceso = MacroProceso.create! valid_attributes
        patch macro_proceso_url(macro_proceso), params: { macro_proceso: new_attributes }
        macro_proceso.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the macro_proceso" do
        macro_proceso = MacroProceso.create! valid_attributes
        patch macro_proceso_url(macro_proceso), params: { macro_proceso: new_attributes }
        macro_proceso.reload
        expect(response).to redirect_to(macro_proceso_url(macro_proceso))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        macro_proceso = MacroProceso.create! valid_attributes
        patch macro_proceso_url(macro_proceso), params: { macro_proceso: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested macro_proceso" do
      macro_proceso = MacroProceso.create! valid_attributes
      expect {
        delete macro_proceso_url(macro_proceso)
      }.to change(MacroProceso, :count).by(-1)
    end

    it "redirects to the macro_procesos list" do
      macro_proceso = MacroProceso.create! valid_attributes
      delete macro_proceso_url(macro_proceso)
      expect(response).to redirect_to(macro_procesos_url)
    end
  end
end
