require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/permiso_documentos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PermisoDocumento. As you add validations to PermisoDocumento, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PermisoDocumento.create! valid_attributes
      get permiso_documentos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      permiso_documento = PermisoDocumento.create! valid_attributes
      get permiso_documento_url(permiso_documento)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_permiso_documento_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      permiso_documento = PermisoDocumento.create! valid_attributes
      get edit_permiso_documento_url(permiso_documento)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PermisoDocumento" do
        expect {
          post permiso_documentos_url, params: { permiso_documento: valid_attributes }
        }.to change(PermisoDocumento, :count).by(1)
      end

      it "redirects to the created permiso_documento" do
        post permiso_documentos_url, params: { permiso_documento: valid_attributes }
        expect(response).to redirect_to(permiso_documento_url(PermisoDocumento.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PermisoDocumento" do
        expect {
          post permiso_documentos_url, params: { permiso_documento: invalid_attributes }
        }.to change(PermisoDocumento, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post permiso_documentos_url, params: { permiso_documento: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested permiso_documento" do
        permiso_documento = PermisoDocumento.create! valid_attributes
        patch permiso_documento_url(permiso_documento), params: { permiso_documento: new_attributes }
        permiso_documento.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the permiso_documento" do
        permiso_documento = PermisoDocumento.create! valid_attributes
        patch permiso_documento_url(permiso_documento), params: { permiso_documento: new_attributes }
        permiso_documento.reload
        expect(response).to redirect_to(permiso_documento_url(permiso_documento))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        permiso_documento = PermisoDocumento.create! valid_attributes
        patch permiso_documento_url(permiso_documento), params: { permiso_documento: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested permiso_documento" do
      permiso_documento = PermisoDocumento.create! valid_attributes
      expect {
        delete permiso_documento_url(permiso_documento)
      }.to change(PermisoDocumento, :count).by(-1)
    end

    it "redirects to the permiso_documentos list" do
      permiso_documento = PermisoDocumento.create! valid_attributes
      delete permiso_documento_url(permiso_documento)
      expect(response).to redirect_to(permiso_documentos_url)
    end
  end
end
