require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/procesos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Proceso. As you add validations to Proceso, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Proceso.create! valid_attributes
      get procesos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      proceso = Proceso.create! valid_attributes
      get proceso_url(proceso)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_proceso_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      proceso = Proceso.create! valid_attributes
      get edit_proceso_url(proceso)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Proceso" do
        expect {
          post procesos_url, params: { proceso: valid_attributes }
        }.to change(Proceso, :count).by(1)
      end

      it "redirects to the created proceso" do
        post procesos_url, params: { proceso: valid_attributes }
        expect(response).to redirect_to(proceso_url(Proceso.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Proceso" do
        expect {
          post procesos_url, params: { proceso: invalid_attributes }
        }.to change(Proceso, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post procesos_url, params: { proceso: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested proceso" do
        proceso = Proceso.create! valid_attributes
        patch proceso_url(proceso), params: { proceso: new_attributes }
        proceso.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the proceso" do
        proceso = Proceso.create! valid_attributes
        patch proceso_url(proceso), params: { proceso: new_attributes }
        proceso.reload
        expect(response).to redirect_to(proceso_url(proceso))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        proceso = Proceso.create! valid_attributes
        patch proceso_url(proceso), params: { proceso: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested proceso" do
      proceso = Proceso.create! valid_attributes
      expect {
        delete proceso_url(proceso)
      }.to change(Proceso, :count).by(-1)
    end

    it "redirects to the procesos list" do
      proceso = Proceso.create! valid_attributes
      delete proceso_url(proceso)
      expect(response).to redirect_to(procesos_url)
    end
  end
end
