require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/seguimiento_solicitudes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SeguimientoSolicitud. As you add validations to SeguimientoSolicitud, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SeguimientoSolicitud.create! valid_attributes
      get seguimiento_solicitudes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      seguimiento_solicitud = SeguimientoSolicitud.create! valid_attributes
      get seguimiento_solicitud_url(seguimiento_solicitud)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_seguimiento_solicitud_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      seguimiento_solicitud = SeguimientoSolicitud.create! valid_attributes
      get edit_seguimiento_solicitud_url(seguimiento_solicitud)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SeguimientoSolicitud" do
        expect {
          post seguimiento_solicitudes_url, params: { seguimiento_solicitud: valid_attributes }
        }.to change(SeguimientoSolicitud, :count).by(1)
      end

      it "redirects to the created seguimiento_solicitud" do
        post seguimiento_solicitudes_url, params: { seguimiento_solicitud: valid_attributes }
        expect(response).to redirect_to(seguimiento_solicitud_url(SeguimientoSolicitud.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SeguimientoSolicitud" do
        expect {
          post seguimiento_solicitudes_url, params: { seguimiento_solicitud: invalid_attributes }
        }.to change(SeguimientoSolicitud, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post seguimiento_solicitudes_url, params: { seguimiento_solicitud: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested seguimiento_solicitud" do
        seguimiento_solicitud = SeguimientoSolicitud.create! valid_attributes
        patch seguimiento_solicitud_url(seguimiento_solicitud), params: { seguimiento_solicitud: new_attributes }
        seguimiento_solicitud.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the seguimiento_solicitud" do
        seguimiento_solicitud = SeguimientoSolicitud.create! valid_attributes
        patch seguimiento_solicitud_url(seguimiento_solicitud), params: { seguimiento_solicitud: new_attributes }
        seguimiento_solicitud.reload
        expect(response).to redirect_to(seguimiento_solicitud_url(seguimiento_solicitud))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        seguimiento_solicitud = SeguimientoSolicitud.create! valid_attributes
        patch seguimiento_solicitud_url(seguimiento_solicitud), params: { seguimiento_solicitud: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested seguimiento_solicitud" do
      seguimiento_solicitud = SeguimientoSolicitud.create! valid_attributes
      expect {
        delete seguimiento_solicitud_url(seguimiento_solicitud)
      }.to change(SeguimientoSolicitud, :count).by(-1)
    end

    it "redirects to the seguimiento_solicitudes list" do
      seguimiento_solicitud = SeguimientoSolicitud.create! valid_attributes
      delete seguimiento_solicitud_url(seguimiento_solicitud)
      expect(response).to redirect_to(seguimiento_solicitudes_url)
    end
  end
end
