require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/solicitud_cambios", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SolicitudCambio. As you add validations to SolicitudCambio, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SolicitudCambio.create! valid_attributes
      get solicitud_cambios_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      solicitud_cambio = SolicitudCambio.create! valid_attributes
      get solicitud_cambio_url(solicitud_cambio)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_solicitud_cambio_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      solicitud_cambio = SolicitudCambio.create! valid_attributes
      get edit_solicitud_cambio_url(solicitud_cambio)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SolicitudCambio" do
        expect {
          post solicitud_cambios_url, params: { solicitud_cambio: valid_attributes }
        }.to change(SolicitudCambio, :count).by(1)
      end

      it "redirects to the created solicitud_cambio" do
        post solicitud_cambios_url, params: { solicitud_cambio: valid_attributes }
        expect(response).to redirect_to(solicitud_cambio_url(SolicitudCambio.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SolicitudCambio" do
        expect {
          post solicitud_cambios_url, params: { solicitud_cambio: invalid_attributes }
        }.to change(SolicitudCambio, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post solicitud_cambios_url, params: { solicitud_cambio: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested solicitud_cambio" do
        solicitud_cambio = SolicitudCambio.create! valid_attributes
        patch solicitud_cambio_url(solicitud_cambio), params: { solicitud_cambio: new_attributes }
        solicitud_cambio.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the solicitud_cambio" do
        solicitud_cambio = SolicitudCambio.create! valid_attributes
        patch solicitud_cambio_url(solicitud_cambio), params: { solicitud_cambio: new_attributes }
        solicitud_cambio.reload
        expect(response).to redirect_to(solicitud_cambio_url(solicitud_cambio))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        solicitud_cambio = SolicitudCambio.create! valid_attributes
        patch solicitud_cambio_url(solicitud_cambio), params: { solicitud_cambio: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested solicitud_cambio" do
      solicitud_cambio = SolicitudCambio.create! valid_attributes
      expect {
        delete solicitud_cambio_url(solicitud_cambio)
      }.to change(SolicitudCambio, :count).by(-1)
    end

    it "redirects to the solicitud_cambios list" do
      solicitud_cambio = SolicitudCambio.create! valid_attributes
      delete solicitud_cambio_url(solicitud_cambio)
      expect(response).to redirect_to(solicitud_cambios_url)
    end
  end
end
