 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tipo_datos", type: :request do
  
  # TipoDato. As you add validations to TipoDato, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TipoDato.create! valid_attributes
      get tipo_datos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tipo_dato = TipoDato.create! valid_attributes
      get tipo_dato_url(tipo_dato)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tipo_dato_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      tipo_dato = TipoDato.create! valid_attributes
      get edit_tipo_dato_url(tipo_dato)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TipoDato" do
        expect {
          post tipo_datos_url, params: { tipo_dato: valid_attributes }
        }.to change(TipoDato, :count).by(1)
      end

      it "redirects to the created tipo_dato" do
        post tipo_datos_url, params: { tipo_dato: valid_attributes }
        expect(response).to redirect_to(tipo_dato_url(TipoDato.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TipoDato" do
        expect {
          post tipo_datos_url, params: { tipo_dato: invalid_attributes }
        }.to change(TipoDato, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tipo_datos_url, params: { tipo_dato: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tipo_dato" do
        tipo_dato = TipoDato.create! valid_attributes
        patch tipo_dato_url(tipo_dato), params: { tipo_dato: new_attributes }
        tipo_dato.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tipo_dato" do
        tipo_dato = TipoDato.create! valid_attributes
        patch tipo_dato_url(tipo_dato), params: { tipo_dato: new_attributes }
        tipo_dato.reload
        expect(response).to redirect_to(tipo_dato_url(tipo_dato))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tipo_dato = TipoDato.create! valid_attributes
        patch tipo_dato_url(tipo_dato), params: { tipo_dato: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tipo_dato" do
      tipo_dato = TipoDato.create! valid_attributes
      expect {
        delete tipo_dato_url(tipo_dato)
      }.to change(TipoDato, :count).by(-1)
    end

    it "redirects to the tipo_datos list" do
      tipo_dato = TipoDato.create! valid_attributes
      delete tipo_dato_url(tipo_dato)
      expect(response).to redirect_to(tipo_datos_url)
    end
  end
end
