require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tipo_sistemas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TipoSistema. As you add validations to TipoSistema, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TipoSistema.create! valid_attributes
      get tipo_sistemas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tipo_sistema = TipoSistema.create! valid_attributes
      get tipo_sistema_url(tipo_sistema)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tipo_sistema_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      tipo_sistema = TipoSistema.create! valid_attributes
      get edit_tipo_sistema_url(tipo_sistema)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TipoSistema" do
        expect {
          post tipo_sistemas_url, params: { tipo_sistema: valid_attributes }
        }.to change(TipoSistema, :count).by(1)
      end

      it "redirects to the created tipo_sistema" do
        post tipo_sistemas_url, params: { tipo_sistema: valid_attributes }
        expect(response).to redirect_to(tipo_sistema_url(TipoSistema.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TipoSistema" do
        expect {
          post tipo_sistemas_url, params: { tipo_sistema: invalid_attributes }
        }.to change(TipoSistema, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tipo_sistemas_url, params: { tipo_sistema: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tipo_sistema" do
        tipo_sistema = TipoSistema.create! valid_attributes
        patch tipo_sistema_url(tipo_sistema), params: { tipo_sistema: new_attributes }
        tipo_sistema.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tipo_sistema" do
        tipo_sistema = TipoSistema.create! valid_attributes
        patch tipo_sistema_url(tipo_sistema), params: { tipo_sistema: new_attributes }
        tipo_sistema.reload
        expect(response).to redirect_to(tipo_sistema_url(tipo_sistema))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tipo_sistema = TipoSistema.create! valid_attributes
        patch tipo_sistema_url(tipo_sistema), params: { tipo_sistema: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tipo_sistema" do
      tipo_sistema = TipoSistema.create! valid_attributes
      expect {
        delete tipo_sistema_url(tipo_sistema)
      }.to change(TipoSistema, :count).by(-1)
    end

    it "redirects to the tipo_sistemas list" do
      tipo_sistema = TipoSistema.create! valid_attributes
      delete tipo_sistema_url(tipo_sistema)
      expect(response).to redirect_to(tipo_sistemas_url)
    end
  end
end
