require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tipo_procesos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TipoProceso. As you add validations to TipoProceso, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TipoProceso.create! valid_attributes
      get tipo_procesos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tipo_proceso = TipoProceso.create! valid_attributes
      get tipo_proceso_url(tipo_proceso)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tipo_proceso_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      tipo_proceso = TipoProceso.create! valid_attributes
      get edit_tipo_proceso_url(tipo_proceso)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TipoProceso" do
        expect {
          post tipo_procesos_url, params: { tipo_proceso: valid_attributes }
        }.to change(TipoProceso, :count).by(1)
      end

      it "redirects to the created tipo_proceso" do
        post tipo_procesos_url, params: { tipo_proceso: valid_attributes }
        expect(response).to redirect_to(tipo_proceso_url(TipoProceso.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TipoProceso" do
        expect {
          post tipo_procesos_url, params: { tipo_proceso: invalid_attributes }
        }.to change(TipoProceso, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tipo_procesos_url, params: { tipo_proceso: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tipo_proceso" do
        tipo_proceso = TipoProceso.create! valid_attributes
        patch tipo_proceso_url(tipo_proceso), params: { tipo_proceso: new_attributes }
        tipo_proceso.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tipo_proceso" do
        tipo_proceso = TipoProceso.create! valid_attributes
        patch tipo_proceso_url(tipo_proceso), params: { tipo_proceso: new_attributes }
        tipo_proceso.reload
        expect(response).to redirect_to(tipo_proceso_url(tipo_proceso))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tipo_proceso = TipoProceso.create! valid_attributes
        patch tipo_proceso_url(tipo_proceso), params: { tipo_proceso: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tipo_proceso" do
      tipo_proceso = TipoProceso.create! valid_attributes
      expect {
        delete tipo_proceso_url(tipo_proceso)
      }.to change(TipoProceso, :count).by(-1)
    end

    it "redirects to the tipo_procesos list" do
      tipo_proceso = TipoProceso.create! valid_attributes
      delete tipo_proceso_url(tipo_proceso)
      expect(response).to redirect_to(tipo_procesos_url)
    end
  end
end
